version: '3.8'
services:
  dockasaurusrx:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: dockasaurusrx
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
      - shared-prometheus-files:/prometheus
      - shared-grafana-files:/grafana
      - grafana-dashboards:/dashboards
    ports:
      - 39870:39870
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 39871:9090
    restart: unless-stopped
    volumes:
      - shared-prometheus-files:/etc/prometheus
      - prometheusdata:/prometheus
    depends_on:
      - dockasaurusrx
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 39872:3000
    volumes:
      - shared-grafana-files:/etc/grafana
      - grafana-dashboards:/etc/dashboards
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus
volumes:
  grafana-dashboards:
  prometheusdata:
  shared-prometheus-files:
  shared-grafana-files:
