apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.docker.internal:39871
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 1s
